[package]
name = "kaleidoscope"
version = "0.1.0"
authors = ["BennyYip <yebenmy@protonmail.com>"]
build = "build.rs"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master" }
llvm-sys = "37.0.5"

